"""scripts/check_glossary_coverage.py

Bold-term glossary coverage scanner.

Purpose:
    Extract all **term** (double-asterisk bold) patterns from governance docs,
    then verify each term appears as a heading or bold entry in docs/glossary.md.
    Reports missing terms and a coverage percentage.

Inputs:
    --files     Paths to governance docs to scan (default: AGENTS.md, MANIFESTO.md,
                docs/guides/*.md relative to workspace root)
    --glossary  Path to glossary file (default: docs/glossary.md)
    --check     Exit 1 if any terms are missing from the glossary
    --fix       Append stub entries for missing terms (idempotent — does not re-add
                terms already present)

Outputs:
    stdout: Coverage report with missing terms and coverage percentage.
    docs/glossary.md: (when --fix) stub entries appended for missing terms.

Exit codes:
    0   All terms covered (or --check not used)
    1   Missing terms found (with --check flag)

Usage examples:
    # Report coverage using defaults
    uv run python scripts/check_glossary_coverage.py

    # Check and exit 1 if gaps found
    uv run python scripts/check_glossary_coverage.py --check

    # Scan specific files
    uv run python scripts/check_glossary_coverage.py --files AGENTS.md MANIFESTO.md

    # Fix: add stubs for missing terms
    uv run python scripts/check_glossary_coverage.py --fix
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

WORKSPACE_ROOT = Path(__file__).parent.parent
DEFAULT_GLOSSARY = WORKSPACE_ROOT / "docs" / "glossary.md"
DEFAULT_FILES = [
    WORKSPACE_ROOT / "AGENTS.md",
    WORKSPACE_ROOT / "MANIFESTO.md",
]


def default_target_files() -> list[Path]:
    """Return default file list: AGENTS.md, MANIFESTO.md, docs/guides/*.md."""
    files = list(DEFAULT_FILES)
    guides_dir = WORKSPACE_ROOT / "docs" / "guides"
    if guides_dir.is_dir():
        files.extend(sorted(guides_dir.glob("*.md")))
    return files


def extract_bold_terms(text: str) -> set[str]:
    """Extract all **term** patterns, returning stripped term strings."""
    pattern = re.compile(r"\*\*([^*\n]+)\*\*")
    terms: set[str] = set()
    for match in pattern.finditer(text):
        term = match.group(1).strip()
        # Skip very short terms or purely punctuation/code strings
        if len(term) < 2:
            continue
        if re.fullmatch(r"[`\s\W]+", term):
            continue
        terms.add(term)
    return terms


def extract_glossary_entries(glossary_text: str) -> set[str]:
    """Extract all heading text and bold terms from glossary (case-insensitive)."""
    entries: set[str] = set()
    for line in glossary_text.splitlines():
        heading_match = re.match(r"^#{1,6}\s+(.+)", line)
        if heading_match:
            entries.add(heading_match.group(1).strip().lower())
        for m in re.finditer(r"\*\*([^*\n]+)\*\*", line):
            entries.add(m.group(1).strip().lower())
    return entries


def term_in_glossary(term: str, glossary_entries: set[str]) -> bool:
    """Lenient case-insensitive match: term appears anywhere in any glossary entry."""
    term_lower = term.lower()
    for entry in glossary_entries:
        if term_lower in entry or entry in term_lower:
            return True
    return False


def check_coverage(
    target_files: list[Path],
    glossary_path: Path,
) -> tuple[set[str], set[str], int]:
    """
    Check bold-term coverage against the glossary.

    Returns:
        (all_terms, missing_terms, files_scanned_count)
    """
    all_terms: set[str] = set()
    scanned = 0
    for path in target_files:
        if path.exists():
            text = path.read_text(encoding="utf-8", errors="replace")
            all_terms.update(extract_bold_terms(text))
            scanned += 1

    if not glossary_path.exists():
        return all_terms, set(all_terms), scanned

    glossary_text = glossary_path.read_text(encoding="utf-8", errors="replace")
    glossary_entries = extract_glossary_entries(glossary_text)

    missing = {t for t in all_terms if not term_in_glossary(t, glossary_entries)}
    return all_terms, missing, scanned


def fix_glossary(missing_terms: set[str], glossary_path: Path) -> int:
    """Append stub entries for missing terms (idempotent)."""
    if not missing_terms:
        print("No missing terms — nothing to fix.")
        return 0

    existing_text = glossary_path.read_text(encoding="utf-8") if glossary_path.exists() else ""
    glossary_entries = extract_glossary_entries(existing_text)

    new_stubs: list[str] = []
    for term in sorted(missing_terms):
        if term_in_glossary(term, glossary_entries):
            continue  # Already present — idempotent
        stub = f"\n## {term}\n\n> _Stub entry — define this term._\n> _Auto-generated by check_glossary_coverage.py_\n"
        new_stubs.append(stub)

    if not new_stubs:
        print("All missing terms already have stubs (idempotent).")
        return 0

    with glossary_path.open("a", encoding="utf-8") as fh:
        fh.write("\n<!-- auto-generated stubs -->\n")
        for stub in new_stubs:
            fh.write(stub)

    print(f"Added {len(new_stubs)} stub(s) to {glossary_path}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Check bold-term coverage in docs/glossary.md")
    parser.add_argument(
        "--files",
        nargs="+",
        default=None,
        help="Governance docs to scan (default: AGENTS.md, MANIFESTO.md, docs/guides/*.md)",
    )
    parser.add_argument(
        "--glossary",
        default=str(DEFAULT_GLOSSARY),
        help="Path to glossary file (default: docs/glossary.md)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if any terms are missing from the glossary",
    )
    parser.add_argument(
        "--fix",
        action="store_true",
        help="Append stub entries for missing terms (idempotent)",
    )
    args = parser.parse_args(argv)

    if args.files:
        target_files = [Path(f) for f in args.files]
    else:
        target_files = default_target_files()

    glossary_path = Path(args.glossary)

    all_terms, missing, files_scanned = check_coverage(target_files, glossary_path)

    total = len(all_terms)
    covered = total - len(missing)
    pct = (covered / total * 100) if total > 0 else 100.0

    print(f"Scanned {files_scanned} file(s) — {total} bold terms found")
    print(f"Coverage: {covered}/{total} ({pct:.1f}%)")

    if missing:
        print(f"\nMissing from glossary ({len(missing)}):")
        for term in sorted(missing):
            print(f"  FAIL  {term}")

    if args.fix:
        fix_glossary(missing, glossary_path)

    if args.check and missing:
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
