#!/usr/bin/env python3
"""Generate coverage badge from test run for pre-commit hook.

**Purpose**: Run pytest with coverage, generate SVG badge, and stage it for commit.

**Inputs**: None (reads from coverage.xml after test run)

**Outputs**:
- coverage.xml (temporary, generated by pytest)
- docs/coverage_badge.svg (staged for commit)

**Exit Codes**:
- 0: Success (badge generated and staged) OR graceful failure (no blocking)
- Never exits non-zero — designed to never block commits

**Usage**:
    # Direct invocation
    uv run python scripts/generate_coverage_badge.py

    # From pre-commit hook (.pre-commit-config.yaml)
    - repo: local
      hooks:
        - id: generate-coverage-badge
          name: Generate coverage badge
          entry: uv run python scripts/generate_coverage_badge.py
          language: system
          pass_filenames: false

**Behavior**:
1. Run pytest with coverage on scripts/ and mcp_server/
2. If coverage.xml exists: generate badge via coverage-badge
3. If badge generated: stage with git add
4. On any failure: exit 0 silently (graceful, don't block commit)

**Rationale**: Pre-commit hooks should enhance workflow, not obstruct it. If badge
generation fails (missing deps, CI environment, etc.), commit proceeds normally.
"""

import subprocess
import sys
from pathlib import Path


def run_command(cmd: list[str], check: bool = False) -> subprocess.CompletedProcess:
    """Run a shell command and return the result.

    Args:
        cmd: Command as list of strings
        check: If True, raise CalledProcessError on non-zero exit

    Returns:
        CompletedProcess with stdout, stderr, and returncode
    """
    return subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        check=check,
    )


def main() -> int:
    """Generate coverage badge from test run.

    Returns:
        Always 0 (graceful exit, never blocks commit)
    """
    try:
        repo_root = Path(__file__).parent.parent
        coverage_xml = repo_root / "coverage.xml"
        badge_path = repo_root / "docs" / "coverage_badge.svg"

        # Step 1: Run pytest with coverage
        print("Running tests with coverage...", flush=True)
        pytest_cmd = ["uv", "run", "pytest", "tests/", "--cov=scripts", "--cov=mcp_server", "--cov-report=xml", "-q"]

        result = run_command(pytest_cmd)
        if result.returncode != 0:
            # Tests failed, but don't block commit
            print("Tests failed, skipping badge generation", file=sys.stderr)
            return 0

        # Step 2: Check if coverage.xml exists
        if not coverage_xml.exists():
            print("coverage.xml not found, skipping badge generation", file=sys.stderr)
            return 0

        # Step 3: Generate badge
        print("Generating coverage badge...", flush=True)
        badge_cmd = ["uv", "run", "coverage-badge", "-o", str(badge_path), "-f"]

        result = run_command(badge_cmd)
        if result.returncode != 0:
            print(f"Badge generation failed: {result.stderr}", file=sys.stderr)
            return 0

        # Step 4: Stage badge for commit
        if badge_path.exists():
            print("Staging coverage badge...", flush=True)
            git_cmd = ["git", "add", str(badge_path)]
            result = run_command(git_cmd)
            if result.returncode != 0:
                print(f"Failed to stage badge: {result.stderr}", file=sys.stderr)
                return 0

            print(f"✓ Coverage badge generated and staged: {badge_path}")

        return 0
    except Exception as e:
        # Graceful failure: log error but don't block commit
        print(f"Coverage badge generation failed: {e}", file=sys.stderr)
        return 0


if __name__ == "__main__":
    sys.exit(main())
